name: test

# Controls when the action will run
# Triggers the workflow on push or pull request
on:
  push:
    branches: [ main, stage ]
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Ensure correct npm version
      run: npm i -g npm@8.3.1 --registry=https://registry.npmjs.org

    - run: npm install

    - run: npm run lint

    - run: npm run testSummary

    - run: npx ts-node .github/workflows/ensureCoverage.ts
